// Tablas curadas de nombres en español para tiles y paredes (IT-09, D02).
// Extraídas de TileDetailPanel para separar datos de presentación, con la
// misma organización que la paleta de F3 (curada + fallback en ficheros de
// datos). El fallback derivado de TerraMap vive en tileNamesFallback.ts.

export const TILE_NAMES: Readonly<Record<number, string>> = {
  0: 'Tierra',
  1: 'Piedra',
  2: 'Cesped',
  3: 'Plantas',
  5: 'Arbol',
  6: 'Mineral de hierro',
  7: 'Mineral de cobre',
  8: 'Mineral de oro',
  9: 'Mineral de plata',
  10: 'Puerta',
  11: 'Puerta',
  12: 'Cristal de vida',
  14: 'Mesa',
  15: 'Silla',
  18: 'Banco de trabajo',
  19: 'Plataforma de madera',
  21: 'Cofre',
  22: 'Mineral de demonita',
  25: 'Ebonstone',
  26: 'Altar',
  27: 'Girasol',
  28: 'Vasija',
  29: 'Hucha',
  30: 'Madera',
  37: 'Meteorito',
  40: 'Obsidiana',
  41: 'Ladrillo azul',
  43: 'Ladrillo verde',
  44: 'Ladrillo rosa',
  45: 'Ladrillo de oro',
  48: 'Pincho',
  50: 'Libro',
  51: 'Telarana',
  53: 'Arena',
  54: 'Cristal',
  55: 'Cartel',
  57: 'Ceniza',
  59: 'Barro',
  60: 'Cesped de jungla',
  79: 'Cama',
  80: 'Cactus',
  81: 'Coral',
  85: 'Lapida',
  88: 'Comoda',
  93: 'Antorcha',
  105: 'Estatua',
  107: 'Mineral de cobalto',
  108: 'Mineral de mithril',
  111: 'Mineral de adamantita',
  147: 'Nieve',
  148: 'Hielo',
  172: 'Lavabo',
  215: 'Hoguera',
  441: 'Cofre',
  467: 'Cofre',
  468: 'Cofre',
  16: 'Yunque',
  17: 'Horno',
  20: 'Brote de arbol',
  23: 'Cesped corrupto',
  24: 'Plantas de corrupcion',
  31: 'Hongo de corrupcion',
  32: 'Espina de corrupcion',
  33: 'Vela',
  34: 'Candelabro',
  35: 'Calabaza de Halloween',
  36: 'Regalo',
  38: 'Piedra gris',
  39: 'Cristal carmesi',
  42: 'Farol colgante',
  46: 'Ladrillo de plata',
  47: 'Ladrillo de cobre',
  49: 'Vela de agua',
  52: 'Enredadera',
  56: 'Ladrillo de obsidiana',
  58: 'Roca infernal',
  62: 'Enredadera de jungla',
  63: 'Zafiro',
  64: 'Rubi',
  65: 'Esmeralda',
  66: 'Topacio',
  67: 'Amatista',
  68: 'Diamante',
  69: 'Arbusto espinoso',
  70: 'Cesped de champinon',
  71: 'Plantas de champinon',
  72: 'Plantas de champinon',
  74: 'Planta',
  75: 'Ladrillo de obsidiana (pared)',
  76: 'Ladrillo de roca infernal',
  77: 'Lampara de lava',
  78: 'Olla de cocina',
  82: 'Hierba madura',
  83: 'Hierba en flor',
  84: 'Hierba',
  86: 'Telar',
  87: 'Piano',
  89: 'Sofa',
  90: 'Farola',
  91: 'Estandarte',
  92: 'Lampara',
  94: 'Banera',
  95: 'Linterna roja',
  96: 'Canon',
  98: 'Candelabro',
  99: 'Estanteria',
  100: 'Trono',
  101: 'Cuenco',
  102: 'Reloj de pie',
  103: 'Estatua',
  104: 'Aserradero',
  106: 'Herreria',
  109: 'Cesped sagrado',
  110: 'Plantas sagradas',
  112: 'Arena ebon',
  113: 'Enredadera sagrada',
  114: 'Yunque de mithril',
  116: 'Arena perla',
  117: 'Piedra perla',
  118: 'Ladrillo de cobalto',
  119: 'Ladrillo de mithril',
  121: 'Ladrillo de cobalto',
  122: 'Ladrillo de mithril',
  123: 'Limo',
  124: 'Viga de madera',
  126: 'Vidrio',
  128: 'Maniqui',
  129: 'Cristal',
  130: 'Piedra activa',
  131: 'Piedra inactiva',
  132: 'Palanca',
  133: 'Forja de adamantita',
  134: 'Yunque de mithril',
  136: 'Interruptor',
  137: 'Trampa',
  138: 'Roca',
  139: 'Caja de musica',
  141: 'Explosivos',
  142: 'Bomba de entrada/salida',
  143: 'Bomba',
  144: 'Temporizador',
  149: 'Luces de Navidad',
  150: 'Ladrillo de adamantita',
  151: 'Ladrillo de arenisca',
  152: 'Madera ebon',
  153: 'Caoba rica',
  154: 'Madera perla',
  155: 'Ladrillo arcoiris',
  156: 'Ladrillo de hielo',
  157: 'Madera sombria',
  158: 'Cesped carmesi',
  159: 'Caoba viva',
  161: 'Hielo fino',
  162: 'Hielo purpura',
  163: 'Hielo rojo',
  164: 'Hielo rosa',
  165: 'Placa de estano',
  166: 'Mineral de estano',
  167: 'Mineral de plomo',
  168: 'Mineral de tungsteno',
  169: 'Mineral de platino',
  170: 'Arbol de Navidad',
  171: 'Arbol de Navidad',
  173: 'Forja del defensor',
  174: 'Altar lihzahrd',
  175: 'Bloque de cobalto',
  176: 'Bloque de mithril',
  177: 'Bloque de platino',
  178: 'Vitrina de gemas',
  179: 'Green Moss',
  180: 'Brown Moss',
  181: 'Red Moss',
  182: 'Blue Moss',
  183: 'Purple Moss',
  381: 'Lava Moss',
  534: 'Krypton Moss',
  536: 'Xenon Moss',
  539: 'Argon Moss',
  687: 'Lava Moss Brick',
  688: 'Argon Moss Brick',
  689: 'Krypton Moss Brick',
  690: 'Xenon Moss Brick',
  691: 'Neon Moss Brick',
  692: 'Helium Moss Brick',
  189: 'Nube',
  190: 'Champinon brillante',
  191: 'Madera viva',
  192: 'Hojas',
  193: 'Bloque de slime',
  194: 'Bloque de hueso',
  195: 'Bloque de carne',
  196: 'Nube de lluvia',
  198: 'Asfalto',
  199: 'Cesped carmesi',
  200: 'Cesped de carne',
  201: 'Roca carmesi',
  202: 'Arena carmesi',
  203: 'Bloque de roca carmesi',
  204: 'Bloque de roca carmesi',
  205: 'Bloque de arena carmesi',
  206: 'Bloque solar',
  207: 'Fuente de agua',
  208: 'Bloque de lava musgo',
  211: 'Mineral de clorofita',
  213: 'Espina de jungla',
  214: 'Bloque de champinon',
  216: 'Lanzacohetes',
  217: 'Extractor de clorofita',
  219: 'Caja fuerte',
  220: 'Linterna de craneo',
  221: 'Solidificador',
  223: 'Cascada',
  224: 'Cascada de lava',
  225: 'Heno',
  226: 'Ladrillo lihzahrd',
  227: 'Planta de tinte',
  228: 'Tanque de tinte',
  229: 'Bloque de miel',
  230: 'Bloque de miel',
  231: 'Colmena',
  254: 'Calabaza',
  272: 'Marmol',
  273: 'Granito',
  274: 'Ladrillo de arenisca',
  396: 'Placa de cobre',
  397: 'Arenisca',
  400: 'Arena ebon endurecida',
  401: 'Arena carmesi endurecida',
  404: 'Arena perla endurecida',
  407: 'Forja del defensor',
  408: 'Marmol',
  411: 'Arena carmesi',
  470: 'Telar',
  471: 'Maquina de coser',
  481: 'Carmesi endurecido',
  482: 'Perla endurecida',
  483: 'Corrupcion endurecida',
  488: 'Comoda',
  489: 'Plataforma de madera sombria',
  490: 'Plataforma de madera perla',
  491: 'Boveda del vacio',
  494: 'Plataforma lihzahrd',
  517: 'Cesped carmesi',
  518: 'Plantas de cesped',
  519: 'Plantas',
  548: 'Arena carmesi',
  574: 'Caoba viva',
  583: 'Estalactita',
  584: 'Estalactita',
  591: 'Mueble',
  621: 'Bloque de cristal',
  622: 'Aether',
  624: 'Losa de arenisca',
  625: 'Neon Moss',
  627: 'Helium Moss',
  629: 'Bloque de subbioma',
  720: 'Lavamoss',
  721: 'Argon moss',
  722: 'Krypton moss',
  723: 'Xenon moss',
  734: 'Bloque de arrecife',
  735: 'Girasol',
};

export const WALL_NAMES: Readonly<Record<number, string>> = {
  1: 'Pared de piedra',
  2: 'Pared de tierra',
  4: 'Pared de madera',
  5: 'Pared de ladrillo gris',
  6: 'Pared de ladrillo rojo',
  7: 'Pared de ladrillo azul',
  8: 'Pared de ladrillo verde',
  9: 'Pared de ladrillo rosa',
  10: 'Pared de ladrillo de oro',
  11: 'Pared de ladrillo de plata',
  12: 'Pared de ladrillo de cobre',
  13: 'Pared de obsidiana',
  14: 'Pared de hellstone',
  30: 'Pared de jungla',
  41: 'Pared de cristal',
  43: 'Pared de telarana',
  44: 'Pared de marmol',
  45: 'Pared de granito',
  54: 'Pared de arenisca',
  70: 'Pared de hielo',
  72: 'Pared de champinon',
  73: 'Pared de nube',
  87: 'Pared de dungeon azul',
  88: 'Pared de dungeon verde',
  89: 'Pared de dungeon rosa',
  3: 'Pared de ebonita',
  15: 'Pared de ladrillo de perla',
  16: 'Pared iridiscente',
  17: 'Pared de ladrillo de lodo',
  18: 'Pared de ladrillo de cobalto',
  19: 'Pared de ladrillo de mithril',
  20: 'Pared de ladrillo de adamantita',
  21: 'Pared de ladrillo de demonita',
  22: 'Losa de piedra',
  23: 'Pared de ladrillo de arenisca',
  24: 'Pared de ladrillo de ebonita',
  25: 'Losa azul',
  26: 'Pared de ladrillo de perla',
  27: 'Pared de ladrillo de nieve',
  28: 'Pared de amatista',
  29: 'Pared de ladrillo carmesi',
  31: 'Pared de flores',
  32: 'Pared de diamante',
  33: 'Pared de caverna',
  34: 'Pared de caverna',
  35: 'Pared de arena',
  36: 'Pared de nieve',
  37: 'Pared de champinon',
  38: 'Pared de demonita',
  39: 'Pared carmesi',
  40: 'Pared carmesi',
  42: 'Pared de confeti',
  46: 'Pared de cristal',
  47: 'Pared de champinon',
  48: 'Pared de caverna',
  49: 'Pared de caverna',
  50: 'Pared de caverna',
  51: 'Pared de caverna',
  52: 'Pared de caverna',
  53: 'Pared de caverna',
  55: 'Pared de cristal',
  56: 'Pared de mithril',
  57: 'Pared de adamantita',
  58: 'Pared de demonita',
  59: 'Pared de cueva',
  60: 'Pared de enredadera de jungla',
  61: 'Pared de madera',
  62: 'Pared de caverna',
  63: 'Pared de jungla',
  64: 'Pared carmesi',
  65: 'Pared de perla',
  66: 'Pared de perla',
  67: 'Pared de perla',
  68: 'Pared de champinon',
  69: 'Pared de telarana',
  71: 'Pared de cristal',
  74: 'Pared solar',
  75: 'Pared solar',
  76: 'Pared de mithril',
  77: 'Pared carmesi',
  78: 'Pared de madera',
  79: 'Pared de champinon',
  80: 'Pared de slime',
  81: 'Pared carmesi',
  82: 'Pared de colmena',
  83: 'Pared de arena',
  84: 'Pared de nieve',
  85: 'Pared de granito',
  86: 'Pared de miel',
  108: 'Pared de miel',
  109: 'Pared carmesi',
  110: 'Pared de demonita',
  111: 'Pared lihzahrd',
  112: 'Pared carmesi',
  113: 'Pared de colmena',
  114: 'Pared de champinon',
  115: 'Pared de cobalto',
  116: 'Pared carmesi',
  117: 'Pared de granito',
  118: 'Pared de jungla',
  119: 'Pared carmesi',
  120: 'Pared de cobalto',
  121: 'Pared de hielo',
  122: 'Pared de caverna',
  123: 'Pared lihzahrd',
  124: 'Pared de jungla',
  125: 'Pared de jungla',
  126: 'Pared de caverna',
  127: 'Pared de estano',
  128: 'Pared de demonita',
  129: 'Pared de cobalto',
  130: 'Pared de mithril',
  131: 'Pared de marmol',
  132: 'Pared demoniaca',
  133: 'Pared de cobalto',
  134: 'Pared de madera',
  136: 'Pared de cobalto',
  137: 'Pared de cobre',
  138: 'Pared de marmol',
  139: 'Pared carmesi',
  140: 'Pared de arenisca',
  141: 'Pared de caverna',
  142: 'Pared de nube',
  143: 'Pared de marmol',
  144: 'Pared de demonita',
  146: 'Pared de madera',
  147: 'Pared de piedra',
  148: 'Pared de perla',
  149: 'Pared de madera',
  151: 'Pared de madera',
  154: 'Pared de demonita',
  155: 'Pared de ladrillo blanco',
  156: 'Pared de cristal',
  157: 'Pared de colmena',
  158: 'Pared de demonita',
  159: 'Pared de caverna',
  160: 'Pared de champinon',
  161: 'Pared carmesi',
  162: 'Pared de cobalto',
  163: 'Pared de colmena',
  164: 'Pared carmesi',
  165: 'Pared de cobalto',
  166: 'Pared solar',
  167: 'Pared de caverna',
  168: 'Pared de marmol',
  170: 'Pared de arenisca',
  171: 'Pared de arenisca',
  175: 'Pared de granito',
  176: 'Pared de caverna',
  187: 'Pared de cobre',
  196: 'Pared de enredadera',
  216: 'Pared de ladrillo lihzahrd',
  217: 'Pared espeluznante',
  224: 'Pared carmesi',
  244: 'Pared de slime rosa',
  246: 'Pared de colmena',
  315: 'Pared brillante',
  316: 'Pared de mazmorra',
  317: 'Pared de mazmorra',
  330: 'Pared de arrecife',
  347: 'Pared sagrada',
  348: 'Pared carmesi',
  349: 'Pared de caverna',
  351: 'Pared solar',
  353: 'Pared de pino',
  94: 'Pared de losa azul',
  95: 'Pared de azulejos azules',
  96: 'Pared de losa rosa',
  97: 'Pared de azulejos rosas',
  98: 'Pared de losa verde',
  99: 'Pared de azulejos verdes',
  200: 'Pared de prisma sagrado',
  201: 'Pared de caverna sagrada',
  202: 'Pared de fragmento sagrado',
  203: 'Pared cristalina sagrada',
  218: 'Pared de arena carmesi endurecida',
  219: 'Pared de arena perla endurecida',
  220: 'Pared de arenisca ebon',
  221: 'Pared de arenisca carmesi',
  222: 'Pared de arenisca perla',
  235: 'Pared de arenisca pulida',
  341: 'Pared de ladrillo de lava moss',
  342: 'Pared de ladrillo de argon moss',
  343: 'Pared de ladrillo de krypton moss',
  344: 'Pared de ladrillo de xenon moss',
  345: 'Pared de ladrillo de neon moss',
  346: 'Pared de ladrillo de helium moss',
};
